---
version: "2.0"

services:
  web:
    image: baktun/akashlytics-web:2.0.0
    env:
      - API_BASE_URL=http://api:80
    expose:
      - port: 3001
        as: 80
        accept:
          - cloudmos.io
          - www.cloudmos.io
        to:
          - global: true
  api:
    image: baktun/akashlytics-api:2.0.0
    env:
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=<GA_TOKEN>
      - HealthchecksEnabled=true
      - AkashlyticsGithubPAT=<GITHUB_PAT>
      - AKASHLYTICS_CORS_WEBSITE_URLS=https://cloudmos.io,https://www.cloudmos.io
    expose:
      - port: 3080
        as: 80
        accept:
          - api.cloudmos.io
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 500mi
        storage:
          size: 500mi
    api:
      resources:
        cpu:
          units: 1
        memory:
          size: 2Gi
        storage:
          size: 60Gi
  placement:
    dcloud:
      pricing:
        web:
          denom: uakt
          amount: 1000
        api:
          denom: uakt
          amount: 1000

deployment:
  web:
    dcloud:
      profile: web
      count: 1
  api:
    dcloud:
      profile: api
      count: 1
