services:
  api:
    build: .
    container_name: akash-analysis-api
    environment:
      - AKASHLYTICS_CORS_WEBSITE_URLS=http://localhost:3080
      - DB_CONNECTION_STRING=postgres://postgres:mysecretpassword@postgres:5432/akash-analysis
    ports:
      - "3080:3080"
    volumes:
      - ./data:/app/data
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5435:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
      
volumes:
  postgres: